---
abstract: 'Simple timer for use with ZeroMQ::Poller'
author:
  - 'James Conerly C<< <james at jamesconerly.com> >>'
build_requires:
  ExtUtils::MakeMaker: 6.42
configure_requires:
  ExtUtils::MakeMaker: 6.42
distribution_type: module
generated_by: 'Module::Install version 0.91'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: ZeroMQ-Poller-Timer
no_index:
  directory:
    - inc
    - t
requires:
  ZeroMQ: 0.17
  threads: 0
resources:
  license: http://dev.perl.org/licenses/
version: 0.01
